pipeline {
    agent any

    environment {
        GIT_URL = 'https://github.com/FranFerreroQA/bug-tracker.git'
        GIT_BRANCH = 'main'
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout') {
            steps {
                deleteDir()
                script {
                    if (isUnix()) {
                        sh '''
                        git clone --branch "$GIT_BRANCH" --single-branch "$GIT_URL" .
                        '''
                    } else {
                        bat '''
                        git clone --branch %GIT_BRANCH% --single-branch %GIT_URL% .
                        '''
                    }
                }
            }
        }

        stage('End-to-End Tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.61.1-jammy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-e2e') {
                    sh '''
                    npm ci
                    npx playwright test
                    '''
                }
            }
            post {
                always {
                    junit 'tests-e2e/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-e2e/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'End-to-End Test Report'
                    ]
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
